use_frameworks!

platform :ios, '8.0'

target 'BuAd_Example' do
  pod 'Masonry'
  pod 'MBProgressHUD'
  pod 'BuAd', :path => '../'

  target 'BuAd_Tests' do
    inherit! :search_paths

    
  end
end
